Authstitchv1
calblueprint/chinese-newcomers pull request #15
Opened 2022-10-16 23:58 UTC by anniehuo

## Documentation
integrated charles firebase auth into screens 
## Related PRs

## Screenshots

CC: @alliu879 @surajr10 @cecilia-gao3

2022-10-22 18:39 UTC, alliu879 requested changes
looks good! just some nits and small things

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Welcome.tsx
> +          onPress={() => navigation.navigate('Sign Up')}
where is this navigating to (what screen)?

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Welcome.tsx
>  const styles = StyleSheet.create({
this should be added to a separate styles file + this welcome screen should be nested within a directory (probably Authentication)

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/styles.tsx
> +  container: {
nit: all styles should be camel case i.e. `verificationContainer` rather than `verificationcontainer`

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/phonenumberinput.tsx
> +import React, { useState, useRef } from 'react';
this should be camel case and should live in `components` rather than `screens/Authentication`

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/Signin.tsx
> +// const auth = getAuth();
please extraneous comments

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/PhoneNumber.tsx
> +  // const { ...phonenumber } = useForm();
remove all extraneous comments

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/AdminRegister.tsx
> +  // const onSubmit: SubmitHandler<FormValues> = async (data) => {
why is this commented out?

2022-10-22 18:39 UTC, alliu879 commented on src/screens/Authentication/AdminRegister.tsx
> +          <TextInput style={styles.input} placeholder=" email@email.com" />
this `TextInput` should be made into a component so we don't have to style this repeatedly

2022-10-22 18:39 UTC, alliu879 commented on src/firebase/firestore/user.ts
> +  const itemsRef = doc(db, 'users', user.id);
nit: rename `itemsRef` should be renamed to something more descriptive

2022-10-22 18:39 UTC, alliu879 commented on src/firebase/firestore/user.ts
> +  const docRef = doc(db, 'users', userId);
see above

2022-10-22 18:39 UTC, alliu879 commented on src/firebase/firestore/user.ts
> +  const docRef = doc(db, 'users', userId);
^^

2022-10-22 19:12 UTC, shannonbonet approved these changes
Left comments on @CharlesMing02 other PR. Comments here mostly for organization

2022-10-22 19:12 UTC, shannonbonet commented on src/firebase/firestore/user.ts
> +    createdJobs: data.createdJobs, //might need to map to job objects later
Have you tested `parseUser` function yet?

2022-10-22 19:12 UTC, shannonbonet commented on src/screens/Authentication/phonenumberinput.tsx
> +const styles = StyleSheet.create({
I noticed an inconsistency with screens/components being styled using StyleSheets in file vs imported from another file. Based on other comments, you sh prob move this to a separate styles file :)

2022-10-30 22:01 UTC, alliu879 approved these changes

2022-10-30 23:00 UTC, merged